version: 1

formatters:
  full:
    format: '%(asctime)s|%(levelname)s - %(message)s'
    datefmt: '%d/%m-%H:%M:%S'

  simple:
    format: '%(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: full
    filename: 'logs/autogrep.log'

loggers:
  base_file:
    level: DEBUG
    handlers: [file]
    propagate: no

  base_console:
    level: CRITICAL
    handlers: [console]
    propagate: no

root:
  level: CRITICAL
  handlers: [console]
